# 1. Matrix Multiplication

Matrix multiplication formula:

If  
$$A = m \times n,\quad B = n \times p$$
then  
$$C = A \cdot B$$
where  
$$C_{ij} = \sum_{k=1}^{n} A_{ik} B_{kj}$$

### Important Rules:
- Inner dimensions *must match* → `A(m×n) * B(n×p)`
- Output is `m×p`



In [57]:
# Matrix Multiplication
def matmul(A, B):
    m, n = len(A), len(A[0])
    n2, p = len(B), len(B[0])
    assert n == n2, "Inner dimensions must match"
    C = [[0]*p for _ in range(m)]

    for i in range(m):
        for j in range(p):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C

print(matmul([[3, 3, 1],[6, 8, 4]],[[3, 2],[6, 2],[5, 3]]))

[[32, 15], [86, 40]]


# 2. Dot Product

Dot product formula:

$$
u \cdot v = \sum_{i=1}^{n} u_i v_i
$$

Geometric meaning:

$$
u \cdot v = |u|\,|v| \cos\theta
$$



In [58]:
# Dot Product
def dot(u, v):
    assert len(u) == len(v), "Vectors must be same length"
    return sum([u[i]*v[i] for i in range(len(u))])

print(dot([3, 3, 1],[3, 6, 5]))

32


# 3. Cross Product (3D Only)

Formula:

$$
u \times v =
\begin{bmatrix}
u_y v_z - u_z v_y \\
u_z v_x - u_x v_z \\
u_x v_y - u_y v_x
\end{bmatrix}
$$

The result is a **vector perpendicular** to both u and v.


In [59]:
# Cross Product 
def cross(u, v):
    assert len(u) == len(v) == 3, "Cross product is 3D only"
    return [
        u[1]*v[2] - u[2]*v[1],
        u[2]*v[0] - u[0]*v[2],
        u[0]*v[1] - u[1]*v[0]
    ]

print(cross([3, 3, 1],[3, 6, 5]))

[9, -12, 9]


# 4. Vector Normalization

Magnitude:

$$
\|v\| = \sqrt{\sum_i v_i^2}
$$

Normalized vector:

$$
\hat{v} = \frac{v}{\|v\|}
$$


In [60]:
# Vector Normalization
import math

def norm(v):
    return math.sqrt(sum([x**2 for x in v]))

def normalize(v):
    n = norm(v)
    return [x/n for x in v] if n != 0 else v

print(normalize([3, 32, 5, 2]))



[0.09205746178983233, 0.9819462590915449, 0.15342910298305387, 0.061371641193221554]


# 5. Singular Value Decomposition (SVD)

SVD breaks a matrix A into:

$$
A = U \Sigma V^T
$$

Where:
- U = left singular vectors
- Σ = singular values
- Vᵀ = right singular vectors

Used in:
- PCA
- 3D reconstruction
- Compression
- Robotics & SLAM


In [61]:
#Singular Value Decomposition (SVD) using NumPy
import numpy as np

A = np.array([[1,2,3],[3,4,5],[5,6,7]])
U, S, VT = np.linalg.svd(A)
print("U:", U)
print("S:", S)
print("VT:", VT)


U: [[-0.2778763   0.86955051  0.40824829]
 [-0.53714153  0.21168918 -0.81649658]
 [-0.79640677 -0.44617216  0.40824829]]
S: [1.31593480e+01 9.11899283e-01 2.46744661e-16]
VT: [[-0.44617216 -0.5686269  -0.69108165]
 [-0.79640677 -0.09998388  0.59643901]
 [-0.40824829  0.81649658 -0.40824829]]


# 6. QR Decomposition (Gram-Schmidt)

We decompose:

$$
A = QR
$$

Where:
- Q = orthonormal basis
- R = upper triangular matrix

Gram-Schmidt removes projection components step by step.


In [62]:
import numpy as np

def qr_gram_schmidt(A):
    A = np.array(A, dtype=float)
    m, n = A.shape
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    
    for j in range(n):
        v = A[:,j].copy()
        for i in range(j):
            R[i,j] = np.dot(Q[:,i], A[:,j])
            v -= R[i,j] * Q[:,i]
        R[j,j] = np.linalg.norm(v)
        Q[:,j] = v / R[j,j]
    return Q, R

print(qr_gram_schmidt([[1,2,3],[3,4,5],[5,6,7]]))

(array([[ 0.16903085,  0.89708523, -0.91736494],
       [ 0.50709255,  0.27602622, -0.2548236 ],
       [ 0.84515425, -0.34503278,  0.30578831]]), array([[5.91607978e+00, 7.43735744e+00, 8.95863510e+00],
       [0.00000000e+00, 8.28078671e-01, 1.65615734e+00],
       [0.00000000e+00, 0.00000000e+00, 2.17841488e-15]]))
